name = "example-nuxt"
main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2023-01-13"
send_metrics = true

[site]
bucket = "./.output/public"

[dev]
port = 4000
local_protocol = "https"

